/**
 * updater.ts
 * ──────────
 * Auto-update module using electron-updater.
 *
 * Workflow:
 *   1. Check for updates silently on app startup
 *   2. If update available, download in background
 *   3. Notify renderer of download progress
 *   4. Apply update on next app restart
 *
 * Uses GitHub Releases as the update server.
 * The update artifacts are generated by electron-builder (nsis installers).
 */

import { autoUpdater, type UpdateInfo } from 'electron-updater';
import { BrowserWindow } from 'electron';
import { APP_NAME } from '../config/constants.js';

// Configure auto-updater
autoUpdater.autoDownload = true;
autoUpdater.autoInstallOnAppQuit = true;
autoUpdater.allowPrerelease = false;
autoUpdater.fullChangelog = true;

/**
 * Initialize the auto-updater.
 * Call this once during app startup (after app.whenReady()).
 */
export function initUpdater(mainWindow: BrowserWindow): void {
  // ── Logging (dev only) ───────────────────────────────
  autoUpdater.logger = {
    info: (msg: string) => {
      if (process.env.NODE_ENV === 'development' || process.env.DEBUG) {
        console.log('[UPDATER]', msg);
      }
    },
    warn: (msg: string) => {
      if (process.env.NODE_ENV === 'development' || process.env.DEBUG) {
        console.warn('[UPDATER]', msg);
      }
    },
    error: (msg: string) => console.error('[UPDATER]', msg),
  };

  // ── Event handlers ───────────────────────────────────

  autoUpdater.on('checking-for-update', () => {
    sendToRenderer(mainWindow, 'update:checking');
  });

  autoUpdater.on('update-available', (info: UpdateInfo) => {
    sendToRenderer(mainWindow, 'update:available', {
      version: info.version,
      releaseDate: info.releaseDate,
      releaseNotes: info.releaseNotes,
    });
  });

  autoUpdater.on('update-not-available', () => {
    sendToRenderer(mainWindow, 'update:not-available');
  });

  autoUpdater.on('download-progress', (progress) => {
    sendToRenderer(mainWindow, 'update:progress', {
      percent: progress.percent,
      bytesPerSecond: progress.bytesPerSecond,
      transferred: progress.transferred,
      total: progress.total,
    });
  });

  autoUpdater.on('update-downloaded', (info: UpdateInfo) => {
    sendToRenderer(mainWindow, 'update:downloaded', {
      version: info.version,
      releaseDate: info.releaseDate,
    });
  });

  autoUpdater.on('error', (error: Error) => {
    sendToRenderer(mainWindow, 'update:error', {
      message: error.message,
    });
  });

  // ── Start checking ──────────────────────────────────
  // Add a small delay to avoid impacting app startup performance
  setTimeout(() => {
    autoUpdater.checkForUpdates().catch(() => {
      // Silently fail — never block app startup
      if (process.env.NODE_ENV === 'development' || process.env.DEBUG) {
        console.warn('[UPDATER] Initial check failed (expected in dev without signed build)');
      }
    });
  }, 3000);
}

/**
 * Check for updates manually (from user "Check for Updates" button).
 */
export function checkForUpdates(): void {
  autoUpdater.checkForUpdates().catch(() => {
    // Silently fail
  });
}

/**
 * Install the downloaded update immediately.
 * The app will restart to apply the update.
 */
export function installUpdate(): void {
  autoUpdater.quitAndInstall(false, true);
}

/**
 * Get the current version.
 */
export function getUpdateStatus(): {
  currentVersion: string;
} {
  return {
    currentVersion: autoUpdater.currentVersion?.format() || 'unknown',
  };
}

// ─── Helper ──────────────────────────────────────────

function sendToRenderer(win: BrowserWindow, channel: string, data?: unknown): void {
  if (win && !win.isDestroyed()) {
    win.webContents.send(channel, data);
  }
}
